numbers=[5,2,1,7,4,5]
numbers.append(20)
print(numbers)
numbers.insert(0,10)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.pop()
print(numbers)
numbers.index(4)
print(numbers)
print(50 in numbers)
print(4 in numbers)
print(numbers.count(5))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)

numbers2=numbers.copy()
print(numbers2)

